version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - id: gopeek
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: gopeek
    main: ./cmd/gopeek/main.go
    flags: -trimpath
    ldflags: -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - id: gopeek
    package_name: gopeek
    vendor: nouuu
    homepage: https://github.com/nouuu/gopeek
    maintainer: nouuu <noelarrieulacoste@yahoo.fr>
    description: Generate a comprehensive view of a project's structure and content
    license: MIT
    formats:
      - deb
      - rpm
      - apk
      - archlinux
    dependencies:
      - git
    recommends:
      - golang
    suggests:
      - make
    section: utils
    priority: optional
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/gopeek/LICENSE

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^vendor:"
      - "^chore:"
      - "^ci:"
