version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

builds:
  - id: gopeek
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: gopeek
    main: ./cmd/gopeek/main.go
    flags: -trimpath
    ldflags: -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - id: gopeek
    package_name: gopeek
    vendor: nouuu
    homepage: https://github.com/nouuu/gopeek
    maintainer: nouuu <noelarrieulacoste@yahoo.fr>
    description: Generate a comprehensive view of a project's structure and content
    license: MIT
    formats:
      - deb
      - rpm
      - apk
      - archlinux
    dependencies:
      - git
    recommends:
      - golang
    suggests:
      - make
    section: utils
    priority: optional
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/gopeek/LICENSE

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^test:"
      - "^vendor:"
  groups:
    - title: '🚀 Features'
      regexp: "^feat[(\\w)]*:.*"
      order: 0
    - title: '🐛 Bug Fixes'
      regexp: "^fix[(\\w)]*:.*"
      order: 1
    - title: '✨ Improvements'
      regexp: "^enhancement[(\\w)]*:.*"
      order: 3
    - title: '📚 Documentation'
      regexp: "^docs[(\\w)]*:.*"
      order: 4
    - title: '🔧 Maintenance'
      regexp: "^chore[(\\w)]*:.*"
      order: 5
    - title: '👷 CI/CD'
      regexp: "^ci[(\\w)]*:.*"
      order: 6
    - title: '🔍 Other Changes'
      order: 999

release:
  draft: false
  prerelease: auto
  name_template: "GoPeek v{{.Version}}"

  header: |
    ## GoPeek Release {{.Version}} 🚀
    
    Generate comprehensive project documentation by scanning your codebase.
    
    ### Quick Start
    
    **Homebrew Tap**
    ```bash
    brew install nouuu/tap/gopeek
    ```
    
    **Go Install**
    ```bash
    go install github.com/nouuu/gopeek@{{.Version}}
    ```
    
    ### Package Managers
    - **Debian/Ubuntu**: Download `.deb` package below
    - **RHEL/Fedora**: Download `.rpm` package below
    - **Alpine**: Download `.apk` package below
    - **Arch Linux**: Download `.pkg.tar.zst` package below

  footer: |
    ### Verify Installation
    
    ```bash
    # Verify SHA-256 checksums
    sha256sum -c checksums.txt
    ```
    
    ### Additional Resources
    - [📚 Documentation](https://github.com/nouuu/gopeek#readme)
    - [🐛 Issue Tracker](https://github.com/nouuu/gopeek/issues)
    - [💡 Feature Requests](https://github.com/nouuu/gopeek/issues/new)
    
    ---
    If you find GoPeek useful, please consider giving it a ⭐️