name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

# Ensure all checks pass before releasing
concurrency:
  group: release
  cancel-in-progress: true

jobs:
  verify:
    name: Verify Checks
    runs-on: ubuntu-latest
    steps:
      - name: Verify build workflow
        uses: actions/checkout@v4
      - name: Check build status
        run: |
          gh run list --workflow=build.yml --branch=${GITHUB_REF#refs/tags/} --json conclusion --jq '.[0].conclusion == "success"' || exit 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check test status
        run: |
          gh run list --workflow=tests.yml --branch=${GITHUB_REF#refs/tags/} --json conclusion --jq '.[0].conclusion == "success"' || exit 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check lint status
        run: |
          gh run list --workflow=lint.yml --branch=${GITHUB_REF#refs/tags/} --json conclusion --jq '.[0].conclusion == "success"' || exit 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check security status
        run: |
          gh run list --workflow=security.yml --branch=${GITHUB_REF#refs/tags/} --json conclusion --jq '.[0].conclusion == "success"' || exit 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  goreleaser:
    name: GoReleaser
    runs-on: ubuntu-latest
    needs:
      - verify
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}