name: security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    name: Security Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.22.x' , '1.23.x' ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run Security Checks
        run: make security

      - name: Upload Security Report
        uses: actions/upload-artifact@v4
        with:
          name: security-report-${{ matrix.go-version }}.json
          path: security-report.json
          if-no-files-found: error